import { LuStar,
  LuLayoutDashboard, LuUsers, LuBuilding2, LuUserRound, LuHandshake,
  LuFileStack, LuWallet, LuMessageCircle, LuSparkles, LuChartColumn,
  LuListChecks, LuSettings, LuShieldCheck, LuNetwork, LuLandmark,
  LuGavel, LuGlobe, LuBriefcase, LuNewspaper, LuDatabase,
  LuKanban, LuActivity, LuSearch, LuChartPie, LuFlame, LuShieldAlert, LuScale, LuBrainCircuit, LuReceipt, LuWaypoints, LuScrollText, LuUserCheck, LuInbox, LuMessagesSquare, LuSchool, LuMegaphone, LuTrophy, LuLanguages, LuMessageSquareText, LuKeyRound, LuArrowLeftRight, LuMapPinned, LuFilePenLine,
} from "react-icons/lu";
import { MODULES } from "./roles";

export const NAV_ITEMS = [
  // Investor workspace (customers only) - `end` keeps Overview from
  // matching every /app/workspace/* route.
  { key: MODULES.WORKSPACE, label: "Overview", to: "/app/workspace", icon: LuLayoutDashboard, end: true },
  { key: MODULES.WORKSPACE, label: "Pipeline", to: "/app/workspace/pipeline", icon: LuKanban },
  { key: MODULES.WORKSPACE, label: "Deal Flow", to: "/app/workspace/deals", icon: LuGavel },
  { key: MODULES.WORKSPACE, label: "Activity", to: "/app/workspace/activity", icon: LuActivity },
  { key: MODULES.WORKSPACE, label: "Saved Searches", to: "/app/workspace/saved", icon: LuSearch },
  { key: MODULES.WORKSPACE, label: "Portfolio", to: "/app/workspace/portfolio", icon: LuChartPie },
  { key: MODULES.DASHBOARD, label: "Dashboard", to: "/app/dashboard", icon: LuLayoutDashboard },
  { key: MODULES.LEADS, label: "Leads", to: "/app/leads", icon: LuHandshake },
  { key: MODULES.ENQUIRIES, label: "Enquiries", to: "/app/enquiries", icon: LuMessagesSquare },
  { key: MODULES.MESSAGES, label: "Messages", to: "/app/messages", icon: LuMessageSquareText },
  { key: MODULES.PROPERTIES, label: "Properties", to: "/app/properties", icon: LuBuilding2 },
  { key: MODULES.CUSTOMERS, label: "Customers", to: "/app/customers", icon: LuUserRound },
  { key: MODULES.BROKERS, label: "Brokers", to: "/app/brokers", icon: LuUsers },
  { key: MODULES.AGENCIES, label: "Agencies", to: "/app/agencies", icon: LuNetwork },
  { key: MODULES.BUILDERS, label: "Builders", to: "/app/builders", icon: LuBuilding2 },
  { key: MODULES.PROJECTS, label: "Projects", to: "/app/projects", icon: LuLandmark },
  { key: MODULES.DEALS, label: "Deal Pipeline", to: "/app/deals", icon: LuChartColumn },
  { key: MODULES.MATCHING, label: "Requirement Marketplace", to: "/app/matching", icon: LuFlame },
  { key: MODULES.TRUST, label: "Trust & Reviews", to: "/app/trust", icon: LuShieldCheck },
  { key: MODULES.REVIEWS, label: "Reviews", to: "/app/reviews", icon: LuStar },
  { key: MODULES.FRAUD, label: "Verification & Fraud", to: "/app/fraud", icon: LuShieldAlert },
  { key: MODULES.COMPLIANCE, label: "Compliance & Risk", to: "/app/compliance", icon: LuShieldAlert },
  { key: MODULES.DISPUTES, label: "Disputes & DD", to: "/app/disputes", icon: LuScale },
  { key: MODULES.INTELLIGENCE, label: "Deal Intelligence", to: "/app/intelligence", icon: LuBrainCircuit },
  { key: MODULES.MANDATES, label: "Mandates", to: "/app/mandates", icon: LuScrollText },
  { key: MODULES.REPRESENTATIVES, label: "Representatives", to: "/app/representatives", icon: LuUserCheck },
  { key: MODULES.LEAD_SOURCES, label: "Lead Sources", to: "/app/lead-sources", icon: LuInbox },
  { key: MODULES.INVOICES, label: "Invoice Centre", to: "/app/invoices", icon: LuReceipt },
  { key: MODULES.REPUTATION, label: "Reputation Graph", to: "/app/reputation", icon: LuWaypoints },
  { key: MODULES.OPPORTUNITIES, label: "Opportunity Deals", to: "/app/opportunities", icon: LuGavel },
  { key: MODULES.FIELD_NETWORK, label: "Field Network", to: "/app/field-network", icon: LuMapPinned },
  { key: MODULES.EXCHANGE, label: "Property Exchange", to: "/app/exchange", icon: LuArrowLeftRight },
  { key: MODULES.INSTITUTIONAL, label: "Institutional", to: "/app/institutional", icon: LuSchool },
  { key: MODULES.INVESTORS, label: "NRI / HNI Investors", to: "/app/investors", icon: LuGlobe },
  { key: MODULES.BUSINESS_LEADS, label: "Business Leads", to: "/app/business-leads", icon: LuBriefcase },
  { key: MODULES.REWARDS, label: "Rewards & Leaderboard", to: "/app/rewards", icon: LuTrophy },
  { key: MODULES.ADVERTISING, label: "Advertising", to: "/app/advertising", icon: LuMegaphone },
  { key: MODULES.TASKS, label: "Tasks & Follow-ups", to: "/app/tasks", icon: LuListChecks },
  { key: MODULES.TEMPLATES, label: "Document Templates", to: "/app/templates", icon: LuFilePenLine },
  { key: MODULES.DOCUMENTS, label: "Documents", to: "/app/documents", icon: LuFileStack },
  { key: MODULES.PAYMENTS, label: "Payments", to: "/app/payments", icon: LuWallet },
  { key: MODULES.WHATSAPP, label: "WhatsApp", to: "/app/whatsapp", icon: LuMessageCircle },
  { key: MODULES.AI, label: "AI Qualification", to: "/app/ai", icon: LuSparkles },
  { key: MODULES.REPORTS, label: "Reports", to: "/app/reports", icon: LuChartColumn },
  { key: MODULES.USERS, label: "Users & Roles", to: "/app/users", icon: LuShieldCheck },
  { key: MODULES.CONTENT, label: "Website Content", to: "/app/content", icon: LuNewspaper },
  { key: MODULES.DEVELOPER, label: "API & Webhooks", to: "/app/developer", icon: LuKeyRound },
  { key: MODULES.LANGUAGES, label: "Languages", to: "/app/languages", icon: LuLanguages },
  { key: MODULES.ADMIN_PANEL, label: "Admin Panel", to: "/app/admin", icon: LuDatabase },
  { key: MODULES.SETTINGS, label: "Settings", to: "/app/settings", icon: LuSettings },
];
